---
- name: Tagging in Ansible --tags=tagged or --tags=untagged
  hosts: all
  tasks:
   - name: Install tree
     apt:
      name: tree
      state: present
     tags: tree_installation
   - name: Create user
     user:
      name: Anu
      password: intelliqit33
     tags: user_creation
   - name: Copy /etc/passwd file
     copy:
      src: /etc/passwd
      dest: /tmp
...
