---
- name: configuring  apache2
  hosts: all
  tasks: 
   - name: installing tomcat10 
     apt :
      name: tomcat10
      state: present 
      update_cache: yes 
   - name: installing tomcat10
     apt :
      name: tomcat10-admin
      state: present
      update_cache: no
   - name: copy file100 
     copy:
      src: file100
      dest: /etc/tomcat10
   - name: changing port
     replace: 
      regexp: 8080 
      replace: 9090 
      path: /etc/tomcat10/server.xml    
   - name: restarting apache2
     service:
      name: tomcat10
      state: restarted
   - name: pause for 1 min 
     pause:
      minutes: 3     
   
   - name: check the tomcat response on server1
     uri:
       url: http://172.31.34.12
       status_code: 200
   - name: check the url response on server2
     uri:
       url: http://172.31.42.189
       status_code: 200

...         
